### PR TITLE
Cashflow data dashboard

### PR DESCRIPTION
**Pull request by saniistamar**

### CODE REVIEW

**Comment by saniistamar** [comment]
it seems to be working as intended but not sure. Samples for returned data can be seen in api/objects. Use the api to fetch data after page load and when the user changes the date range. API accepts query params "from", "until" and "type". will explain more later.

**Comment by saniistamar** [comment]
I will not be pushing any further commits here until work has begun on the frontend and my assistance would be beneficial.

**Comment by Tx-ID** [comment]
im deadass in the bed rn

edit: will do tomorrow morn

**Comment by Tx-ID** [comment]
i did something, now go wild

**Comment by saniistamar** [comment]
idih keren banget

**Pull request merged**
